// ─────────────────────────────────────────────
// MENÚ COMPLETO
// ─────────────────────────────────────────────
export const MENU = {
  bar: {
    'Licores': [
      { id: 'b_añejo_1800', name: '1800 Añejo', price: 3000, category: 'alcoholic' },
      { id: 'b_blanco_1800', name: '1800 Blanco', price: 2500, category: 'alcoholic' },
      { id: 'b_reposado_1800', name: '1800 Reposado', price: 2500, category: 'alcoholic' },
      { id: 'b_absolut', name: 'Absolut', price: 2000, category: 'alcoholic' },
      { id: 'b_amarula', name: 'Amarula', price: 2000, category: 'alcoholic' },
      { id: 'b_antioq_azul', name: 'Antioqueño Azul', price: 2000, category: 'alcoholic' },
      { id: 'b_antioq_rojo', name: 'Antioqueño Rojo', price: 2000, category: 'alcoholic' },
      { id: 'b_antioq_verde', name: 'Antioqueño Verde', price: 2000, category: 'alcoholic' },
      { id: 'b_anis_imperial', name: 'Anís Imperial', price: 1500, category: 'alcoholic' },
      { id: 'b_bacardi', name: 'Bacardi', price: 1500, category: 'alcoholic' },
      { id: 'b_ballantines', name: 'Ballantines', price: 2000, category: 'alcoholic' },
      { id: 'b_baileys', name: 'Baileys', price: 2000, category: 'alcoholic' },
      { id: 'b_black_white', name: 'Black & White', price: 1500, category: 'alcoholic' },
      { id: 'b_buchanans', name: "Buchanan's", price: 3000, category: 'alcoholic' },
      { id: 'b_cacique', name: 'Cacique', price: 1000, category: 'alcoholic' },
      { id: 'b_campari', name: 'Campari', price: 2000, category: 'alcoholic' },
      { id: 'b_captain_morgan', name: 'Captain Morgan', price: 1500, category: 'alcoholic' },
      { id: 'b_centenario', name: 'Centenario', price: 1500, category: 'alcoholic' },
      { id: 'b_chivas_regal', name: 'Chivas Regal', price: 2200, category: 'alcoholic' },
      { id: 'b_don_julio', name: 'Don Julio', price: 5000, category: 'alcoholic' },
    ],
    'Cervezas Nacionales': [
      { id: 'b_imperial', name: 'Imperial', price: 1500, category: 'beverage' },
      { id: 'b_pilsen', name: 'Pilsen', price: 1500, category: 'beverage' },
      { id: 'b_silver', name: 'Silver', price: 1500, category: 'beverage' },
      { id: 'b_light', name: 'Light', price: 1500, category: 'beverage' },
      { id: 'b_ultra', name: 'Ultra', price: 1500, category: 'beverage' },
      { id: 'b_rock_ice', name: 'Rock Ice', price: 1700, category: 'beverage' },
    ],
    'Preparados': [
      { id: 'b_michelada', name: 'Michelada', price: 1700, category: 'beverage' },
      { id: 'b_adan_eva', name: 'Adán y Eva', price: 2000, category: 'beverage' },
      { id: 'b_smirnoff_ice', name: 'Smirnoff Ice', price: 2000, category: 'beverage' },
      { id: 'b_cuba_libre', name: 'Cuba Libre', price: 2000, category: 'beverage' },
      { id: 'b_bamboo', name: 'Bamboo', price: 2000, category: 'beverage' },
    ],
    'Cervezas Importadas': [
      { id: 'b_bavaria', name: 'Bavaria', price: 2000, category: 'beverage' },
      { id: 'b_sol', name: 'Sol', price: 2000, category: 'beverage' },
      { id: 'b_budweiser', name: 'Budweiser', price: 2000, category: 'beverage' },
      { id: 'b_corona', name: 'Corona', price: 2000, category: 'beverage' },
      { id: 'b_corona_cero', name: 'Corona Cero', price: 2000, category: 'beverage' },
      { id: 'b_bud_light', name: 'Bud Light', price: 2000, category: 'beverage' },
      { id: 'b_modelo', name: 'Modelo', price: 2000, category: 'beverage' },
      { id: 'b_heineken', name: 'Heineken', price: 2000, category: 'beverage' },
      { id: 'b_heineken_cero', name: 'Heineken Cero', price: 2000, category: 'beverage' },
      { id: 'b_stella', name: 'Stella', price: 2000, category: 'beverage' },
      { id: 'b_toña', name: 'Toña', price: 2000, category: 'beverage' },
    ],
    'Sin Alcohol': [
      { id: 'b_refrescos', name: 'Refrescos', price: 1500, category: 'soda' },
      { id: 'b_jugos', name: 'Jugos', price: 1500, category: 'soda' },
      { id: 'b_jugo_tomate', name: 'Jugo de Tomate', price: 1500, category: 'soda' },
      { id: 'b_tropicales', name: 'Tropicales', price: 1500, category: 'soda' },
      { id: 'b_aloe', name: 'Aloe', price: 2000, category: 'soda' },
    ],
    'Arroz con': [
      { id: 'f_arroz_pollo', name: 'Arroz con Pollo', price: 3900, category: 'food' },
      { id: 'f_arroz_carne', name: 'Arroz con Carne', price: 4000, category: 'food' },
      { id: 'f_arroz_camarones', name: 'Arroz con Camarones', price: 4300, category: 'food' },
    ],
    'Surtido': [
      { id: 'f_surtido_grande', name: 'Grande', price: 10400, category: 'food' },
      { id: 'f_surtido_pequeno', name: 'Pequeño', price: 8400, category: 'food' },
    ],
    'Bocas': [
      { id: 'f_carne_salsa', name: 'Carne en salsa', price: 3000, category: 'food' },
      { id: 'f_frijoles_pezuna', name: 'Frijoles con pezuña', price: 2200, category: 'food' },
      { id: 'f_chifrijo', name: 'Chifrijo', price: 3200, category: 'food' },
      { id: 'f_ceviche', name: 'Ceviche', price: 3000, category: 'food' },
    ],
    'Comida rápida': [
      { id: 'f_burritos_carne', name: 'Burritos de carne', price: 4000, category: 'food', canHavePapas: true },
      { id: 'f_burrito_pollo', name: 'Burrito de pollo', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_burrito_mixto', name: 'Burrito mixto', price: 4300, category: 'food', canHavePapas: true },
      { id: 'f_alitas', name: 'Alitas (6)', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_filet_pescado', name: 'Filet de pescado', price: 3300, category: 'food', canHavePapas: true },
      { id: 'f_hamb_pollo', name: 'Hamburguesa de pollo', price: 2500, category: 'food' },
      { id: 'f_hamb_pollo_papas', name: 'Hamburguesa de pollo con papas', price: 3000, category: 'food' },
      { id: 'f_hamb_lore', name: 'Hamburguesa Lore', price: 3000, category: 'food' },
      { id: 'f_hamb_lore_papas', name: 'Hamburguesa Lore y papas', price: 3500, category: 'food' },
      { id: 'f_costilla_bbq', name: 'Costilla BBQ', price: 4500, category: 'food', canHavePapas: true },
      { id: 'f_chalupas_carne', name: 'Chalupas de carne', price: 3000, category: 'food', canHavePapas: true },
      { id: 'f_chalupas_pollo', name: 'Chalupas de pollo', price: 2800, category: 'food', canHavePapas: true },
      { id: 'f_chalupas_mixtas', name: 'Chalupas mixtas', price: 3300, category: 'food', canHavePapas: true },
      { id: 'f_pechuga', name: 'Pechuga frita', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_hamburguesa', name: 'Hamburguesa', price: 1500, category: 'food' },
      { id: 'f_hamburguesa_papas', name: 'Hamburguesa con papas', price: 2300, category: 'food' },
      { id: 'f_nachos_carne', name: 'Nachos de carne', price: 4000, category: 'food' },
      { id: 'f_nachos_pollo', name: 'Nachos de pollo', price: 3900, category: 'food' },
      { id: 'f_nachos_mixtos', name: 'Nachos mixtos', price: 4300, category: 'food' },
      { id: 'f_papas_carne', name: 'Papas supremas carne', price: 4000, category: 'food' },
      { id: 'f_papas_pollo', name: 'Papas supremas pollo', price: 3900, category: 'food' },
      { id: 'f_papas_mixtas', name: 'Papas supremas mixtas', price: 4300, category: 'food' },
      { id: 'f_papas_grandes', name: 'Papas grandes', price: 2000, category: 'food' },
      { id: 'f_tacos', name: 'Orden de tacos', price: 1500, category: 'food' },
      { id: 'f_salchipapas', name: 'Salchipapas', price: 2800, category: 'food' },
      { id: 'f_costilla_frita', name: 'Costilla frita', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_fajitas_pollo', name: 'Fajitas de pollo', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_fajitas_emp', name: 'Fajitas empanizadas', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_fajitas_res', name: 'Fajitas de res', price: 4000, category: 'food', canHavePapas: true },
      { id: 'f_quesadilla_carne', name: 'Quesadilla de carne', price: 4000, category: 'food', canHavePapas: true },
      { id: 'f_quesadilla_pollo', name: 'Quesadilla de pollo', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_quesadilla_mixta', name: 'Quesadilla mixta', price: 4300, category: 'food', canHavePapas: true },
      { id: 'f_patacon_carne', name: 'Patacón supremo carne', price: 4000, category: 'food' },
      { id: 'f_patacon_pollo', name: 'Patacón supremo pollo', price: 3900, category: 'food' },
      { id: 'f_patacon_mixto', name: 'Patacón supremo mixto', price: 4300, category: 'food' },
    ],
    'Menú de niños': [
      { id: 'f_deditos_pollo', name: 'Deditos de pollo', price: 2300, category: 'food' },
      { id: 'f_deditos_pescado', name: 'Deditos de pescado', price: 2300, category: 'food' },
      { id: 'f_papas_pequenas', name: 'Papas pequeñas', price: 1000, category: 'food' },
      { id: 'f_nino_nachos', name: 'Niño nachos', price: 2300, category: 'food' },
    ],
  },
  restaurante: {
    'Licores': [
      { id: 'r_añejo_1800', name: '1800 Añejo', price: 3000, category: 'alcoholic' },
      { id: 'r_blanco_1800', name: '1800 Blanco', price: 2500, category: 'alcoholic' },
      { id: 'r_reposado_1800', name: '1800 Reposado', price: 2500, category: 'alcoholic' },
      { id: 'r_absolut', name: 'Absolut', price: 2000, category: 'alcoholic' },
      { id: 'r_amarula', name: 'Amarula', price: 2000, category: 'alcoholic' },
      { id: 'r_antioq_azul', name: 'Antioqueño Azul', price: 2000, category: 'alcoholic' },
      { id: 'r_antioq_rojo', name: 'Antioqueño Rojo', price: 2000, category: 'alcoholic' },
      { id: 'r_antioq_verde', name: 'Antioqueño Verde', price: 2000, category: 'alcoholic' },
      { id: 'r_anis_imperial', name: 'Anís Imperial', price: 1500, category: 'alcoholic' },
      { id: 'r_bacardi', name: 'Bacardi', price: 1500, category: 'alcoholic' },
      { id: 'r_ballantines', name: 'Ballantines', price: 2000, category: 'alcoholic' },
      { id: 'r_baileys', name: 'Baileys', price: 2000, category: 'alcoholic' },
      { id: 'r_black_white', name: 'Black & White', price: 1500, category: 'alcoholic' },
      { id: 'r_buchanans', name: "Buchanan's", price: 3000, category: 'alcoholic' },
      { id: 'r_cacique', name: 'Cacique', price: 1000, category: 'alcoholic' },
      { id: 'r_campari', name: 'Campari', price: 2000, category: 'alcoholic' },
      { id: 'r_captain_morgan', name: 'Captain Morgan', price: 1500, category: 'alcoholic' },
      { id: 'r_centenario', name: 'Centenario', price: 1500, category: 'alcoholic' },
      { id: 'r_chivas_regal', name: 'Chivas Regal', price: 2200, category: 'alcoholic' },
      { id: 'r_don_julio', name: 'Don Julio', price: 5000, category: 'alcoholic' },
    ],
    'Cervezas Nacionales': [
      { id: 'r_imperial', name: 'Imperial', price: 1500, category: 'beverage' },
      { id: 'r_pilsen', name: 'Pilsen', price: 1500, category: 'beverage' },
      { id: 'r_silver', name: 'Silver', price: 1500, category: 'beverage' },
      { id: 'r_light', name: 'Light', price: 1500, category: 'beverage' },
      { id: 'r_ultra', name: 'Ultra', price: 1500, category: 'beverage' },
      { id: 'r_rock_ice', name: 'Rock Ice', price: 1700, category: 'beverage' },
    ],
    'Preparados': [
      { id: 'r_michelada', name: 'Michelada', price: 1700, category: 'beverage' },
      { id: 'r_adan_eva', name: 'Adán y Eva', price: 2000, category: 'beverage' },
      { id: 'r_smirnoff_ice', name: 'Smirnoff Ice', price: 2000, category: 'beverage' },
      { id: 'r_cuba_libre', name: 'Cuba Libre', price: 2000, category: 'beverage' },
      { id: 'r_bamboo', name: 'Bamboo', price: 2000, category: 'beverage' },
    ],
    'Cervezas Importadas': [
      { id: 'r_bavaria', name: 'Bavaria', price: 2000, category: 'beverage' },
      { id: 'r_sol', name: 'Sol', price: 2000, category: 'beverage' },
      { id: 'r_budweiser', name: 'Budweiser', price: 2000, category: 'beverage' },
      { id: 'r_corona', name: 'Corona', price: 2000, category: 'beverage' },
      { id: 'r_corona_cero', name: 'Corona Cero', price: 2000, category: 'beverage' },
      { id: 'r_bud_light', name: 'Bud Light', price: 2000, category: 'beverage' },
      { id: 'r_modelo', name: 'Modelo', price: 2000, category: 'beverage' },
      { id: 'r_heineken', name: 'Heineken', price: 2000, category: 'beverage' },
      { id: 'r_heineken_cero', name: 'Heineken Cero', price: 2000, category: 'beverage' },
      { id: 'r_stella', name: 'Stella', price: 2000, category: 'beverage' },
      { id: 'r_toña', name: 'Toña', price: 2000, category: 'beverage' },
    ],
    'Sin Alcohol': [
      { id: 'r_gaseosa_vidrio', name: 'Gaseosa Vidrio', price: 1000, category: 'soda' },
      { id: 'r_gaseosa_600', name: 'Gaseosa 600ml', price: 1500, category: 'soda' },
      { id: 'r_gaseosa_345', name: 'Gaseosa 345ml', price: 700, category: 'soda' },
      { id: 'r_gaseosa_1500', name: 'Gaseosa 1.5L', price: 2000, category: 'soda' },
      { id: 'r_tropical_vidrio', name: 'Tropical Vidrio', price: 1000, category: 'soda' },
      { id: 'r_refrescos', name: 'Refrescos', price: 1500, category: 'soda' },
      { id: 'r_jugos', name: 'Jugos', price: 1500, category: 'soda' },
      { id: 'r_jugo_tomate', name: 'Jugo de Tomate', price: 1500, category: 'soda' },
      { id: 'r_aloe', name: 'Aloe', price: 2000, category: 'soda' },
    ],
    'Arroz con': [
      { id: 'f_arroz_pollo', name: 'Arroz con Pollo', price: 3900, category: 'food' },
      { id: 'f_arroz_carne', name: 'Arroz con Carne', price: 4000, category: 'food' },
      { id: 'f_arroz_camarones', name: 'Arroz con Camarones', price: 4300, category: 'food' },
    ],
    'Surtido': [
      { id: 'f_surtido_grande', name: 'Grande', price: 10400, category: 'food' },
      { id: 'f_surtido_pequeno', name: 'Pequeño', price: 8400, category: 'food' },
    ],
    'Bocas': [
      { id: 'f_carne_salsa', name: 'Carne en salsa', price: 3000, category: 'food' },
      { id: 'f_frijoles_pezuna', name: 'Frijoles con pezuña', price: 2200, category: 'food' },
      { id: 'f_chifrijo', name: 'Chifrijo', price: 3200, category: 'food' },
      { id: 'f_ceviche', name: 'Ceviche', price: 3000, category: 'food' },
    ],
    'Comida rápida': [
      { id: 'f_burritos_carne', name: 'Burritos de carne', price: 4000, category: 'food', canHavePapas: true },
      { id: 'f_burrito_pollo', name: 'Burrito de pollo', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_burrito_mixto', name: 'Burrito mixto', price: 4300, category: 'food', canHavePapas: true },
      { id: 'f_alitas', name: 'Alitas (6)', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_filet_pescado', name: 'Filet de pescado', price: 3300, category: 'food', canHavePapas: true },
      { id: 'f_hamb_pollo', name: 'Hamburguesa de pollo', price: 2500, category: 'food' },
      { id: 'f_hamb_pollo_papas', name: 'Hamburguesa de pollo con papas', price: 3000, category: 'food' },
      { id: 'f_hamb_lore', name: 'Hamburguesa Lore', price: 3000, category: 'food' },
      { id: 'f_hamb_lore_papas', name: 'Hamburguesa Lore y papas', price: 3500, category: 'food' },
      { id: 'f_costilla_bbq', name: 'Costilla BBQ', price: 4500, category: 'food', canHavePapas: true },
      { id: 'f_chalupas_carne', name: 'Chalupas de carne', price: 3000, category: 'food', canHavePapas: true },
      { id: 'f_chalupas_pollo', name: 'Chalupas de pollo', price: 2800, category: 'food', canHavePapas: true },
      { id: 'f_chalupas_mixtas', name: 'Chalupas mixtas', price: 3300, category: 'food', canHavePapas: true },
      { id: 'f_pechuga', name: 'Pechuga frita', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_hamburguesa', name: 'Hamburguesa', price: 1500, category: 'food' },
      { id: 'f_hamburguesa_papas', name: 'Hamburguesa con papas', price: 2300, category: 'food' },
      { id: 'f_nachos_carne', name: 'Nachos de carne', price: 4000, category: 'food' },
      { id: 'f_nachos_pollo', name: 'Nachos de pollo', price: 3900, category: 'food' },
      { id: 'f_nachos_mixtos', name: 'Nachos mixtos', price: 4300, category: 'food' },
      { id: 'f_papas_carne', name: 'Papas supremas carne', price: 4000, category: 'food' },
      { id: 'f_papas_pollo', name: 'Papas supremas pollo', price: 3900, category: 'food' },
      { id: 'f_papas_mixtas', name: 'Papas supremas mixtas', price: 4300, category: 'food' },
      { id: 'f_papas_grandes', name: 'Papas grandes', price: 2000, category: 'food' },
      { id: 'f_tacos', name: 'Orden de tacos', price: 1500, category: 'food' },
      { id: 'f_salchipapas', name: 'Salchipapas', price: 2800, category: 'food' },
      { id: 'f_costilla_frita', name: 'Costilla frita', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_fajitas_pollo', name: 'Fajitas de pollo', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_fajitas_emp', name: 'Fajitas empanizadas', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_fajitas_res', name: 'Fajitas de res', price: 4000, category: 'food', canHavePapas: true },
      { id: 'f_quesadilla_carne', name: 'Quesadilla de carne', price: 4000, category: 'food', canHavePapas: true },
      { id: 'f_quesadilla_pollo', name: 'Quesadilla de pollo', price: 3900, category: 'food', canHavePapas: true },
      { id: 'f_quesadilla_mixta', name: 'Quesadilla mixta', price: 4300, category: 'food', canHavePapas: true },
      { id: 'f_patacon_carne', name: 'Patacón supremo carne', price: 4000, category: 'food' },
      { id: 'f_patacon_pollo', name: 'Patacón supremo pollo', price: 3900, category: 'food' },
      { id: 'f_patacon_mixto', name: 'Patacón supremo mixto', price: 4300, category: 'food' },
    ],
    'Menú de niños': [
      { id: 'f_deditos_pollo', name: 'Deditos de pollo', price: 2300, category: 'food' },
      { id: 'f_deditos_pescado', name: 'Deditos de pescado', price: 2300, category: 'food' },
      { id: 'f_papas_pequenas', name: 'Papas pequeñas', price: 1000, category: 'food' },
      { id: 'f_nino_nachos', name: 'Niño nachos', price: 2300, category: 'food' },
    ],
  },
};

// ─────────────────────────────────────────────
// PINES DE ACCESO
// ─────────────────────────────────────────────
export const PINES = {
  'Caja Bar':           { pin: '1970', role: 'caja',   zone: 'bar' },
  'Caja Restaurante':   { pin: '1969', role: 'caja',   zone: 'restaurante' },
  'Tablet Restaurante': { pin: '7878', role: 'mesera', zone: 'restaurante' },
  'Cocina':             { pin: '7878', role: 'cocina', zone: 'restaurante' },
  'María':              { pin: '5456', role: 'mesera', zone: 'bar' },
  'Milena':             { pin: '8995', role: 'mesera', zone: 'bar' },
  'Lin':                { pin: '7777', role: 'mesera', zone: 'bar' },
  'Temp Bar':           { pin: '1221', role: 'mesera', zone: 'bar' },
  'Admin':              { pin: '0000', role: 'admin',  zone: 'admin' },
};

export const meseras = ['María', 'Milena', 'Lin', 'Temp Bar'];
export const barras  = ['Barra 1', 'Barra 2', 'Barra 3', 'Barra Grande'];
